//移植工作主要有以下部分（仅仅对未作处理的部分做阐述）：
//
//1.在mach-smdk6410.c这个文件中添加初始化的设备
//
//&s3c_device_fb,
//
//会根据name 自动关联执行哪个设备的probe的探测函数
//
// 
//
//同时在plat-s3c64XX下面增加dev-fb.c 主要是用来填充platform_fb这个结构体
//  


//======================打开注释回车   /*=========================  
    
static struct resource s3cfb_resource[] = {
 [0] = {
  .start = S3C64XX_PA_LCD,
  .end   = S3C64XX_PA_LCD + S3C64XX_SZ_LCD - 1,
  .flags = IORESOURCE_MEM,
 },
 [1] = {
  .start = IRQ_LCD_VSYNC,
  .end   = IRQ_LCD_VSYNC,
  .flags = IORESOURCE_IRQ,
 },
 [2] = {
  .start = IRQ_LCD_FIFO,
  .end   = IRQ_LCD_FIFO,
  .flags = IORESOURCE_IRQ,
 },
};

static u64 fb_dma_mask = 0xffffffffUL;

struct platform_device s3c_device_fb = {
 .name    = "s3cfb",
 .id    = -1,
 .num_resources   = ARRAY_SIZE(s3cfb_resource),
 .resource   = s3cfb_resource,
 .dev              = {
  .dma_mask  = &fb_dma_mask,
  .coherent_dma_mask = 0xffffffffUL
 }
};

static struct s3c_platform_fb default_fb_data __initdata = {
 .hw_ver = 0x40,
 .clk_name = "lcd",
 .nr_wins = 5,
 .default_win = 1,//CONFIG_FB_S3C_V2_DEFAULT_WINDOW,
 .swap = FB_SWAP_HWORD,
};

void __init s3cfb_set_platdata(struct s3c_platform_fb *pd)
{
 struct s3c_platform_fb *npd;
 int i;

 if (!pd)
  pd = &default_fb_data;
 npd = kmemdup(pd, sizeof(struct s3c_platform_fb), GFP_KERNEL);
 if (!npd)
  printk(KERN_ERR "%s: no memory for platform data\n", __func__);

 for (i = 0; i < npd->nr_wins; i++)
  npd->nr_buffers[i] = 1;

 npd->nr_buffers[npd->default_win] = 1 + 1;

 npd->cfg_gpio = s3cfb_cfg_gpio;
 npd->backlight_on = s3cfb_backlight_on;
 npd->reset_lcd = s3cfb_reset_lcd;

 s3c_device_fb.dev.platform_data = npd;
}


//在machine_init的时候执行s3cfb_set_platdata(NULL);就已经填充完毕
//
//.clk_name = "lcd", 在填充时候就已经把对应LCD所需的clk指向其具体的clk(CPU.c中有相关的结构体的填充)
//
//所有的时钟都是在cpu.c中配置的！具体的时钟实现是在对应平台下的clock.c配置
//
//
//
//2)mach-s3c6400\include\mach\memory.h 中增加了
//    #define CONSISTENT_DMA_SIZE (SZ_8M + SZ_4M + SZ_2M)
//    #define __virt_to_bus(x) __virt_to_phys(x)
//    #define __bus_to_virt(x) __phys_to_virt(x)
//   
//  如果不定义这个的话默认为2M，会导致DMA太小溢出
//
//3）删除mach-smdk6410.c中设置LCD， Gpio_request会导致后面initial时候gpio-request失败，（重复调用）
//
#if 0   
 gpio_request(S3C64XX_GPN(5), "LCD power");
 gpio_request(S3C64XX_GPF(13), "LCD power");
 gpio_request(S3C64XX_GPF(15), "LCD power");
#endif

//以下是删除设置LCD的类型，以为在probe时候已经配置好了，各版本内核的架构不一样，所以初始化的位置也就不相同，以后续高版本为准，
//
 
#if 0
 tmp = __raw_readl(S3C64XX_SPCON);
 tmp &= ~S3C64XX_SPCON_LCD_SEL_MASK;
 tmp |= S3C64XX_SPCON_LCD_SEL_RGB;
 __raw_writel(tmp, S3C64XX_SPCON);

 
 tmp = __raw_readl(S3C64XX_MODEM_MIFPCON);
 tmp &= ~MIFPCON_LCD_BYPASS;
 __raw_writel(tmp, S3C64XX_MODEM_MIFPCON);
#endif 

 

//4)plat-s3c24xx\include\plat\clock.h 增加了clock.h这个文件，因为24xx和64xx在部分功能和接口是一样的，函数可以互相调用
//
// 
//
//5)plat-s3c64xx\include\plat\pll.h   regs-gpio.h 定义了时钟和pin脚相关的宏以及函数
//
//6）修改asm/fb.h
//static inline int fb_is_primary_device(struct fb_info *info)
//{
// return 0;
//}

extern int fb_is_primary_device(struct fb_info *info);

fb_is_primary_device 是调用S3cfb.c中的函数而不是直接返回0

//这一步至关重要，因为在后面framebuffer_register时候会有个判断，就是是使用那一个fb设备作为当前设备，
//
// 
//
// 
//
//大概的移植需要这些步骤，但是有些函数和头文件是直接在原文件上更改的，标记做的不全，所以也就不详细的写了
             
             
             
             
             
//linux2.6.28下6410LCD驱动分析                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
//[ 2010-5-4 2:52:00 | By: 急驰的蚂蚁 ]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//    本文不详细分析lcd的每行代码 ，只是做简单的构架分析，   要详细的分析可以参考http://www.cnitblog.com/luofuchong/archive/2007/10/30/35570.html，里面虽然是多2410的分析，但都大同小异。                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//    LCD驱动是用了device 和driver架构，首先看arch/arm/mach-s3c6410/mach-smdk6410.c文件，在353行有这样一个数组                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
static struct platform_device *smdk6410_devices[] __initdata = {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
……………………                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
&s3c_device_lcd,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
……………………                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//我们在进里面了解详情，在arch/arm/palt-s3c64xx/devs.c文件里有s3c_device_lcd变量的定义                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
static struct resource s3c_lcd_resource[] = {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 [0] = {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  .start = S3C64XX_PA_LCD,                          //lcd寄存器的起始地址                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  .end   = S3C64XX_PA_LCD + SZ_1M - 1,    //lcd寄存器的结束地址，                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
  .flags = IORESOURCE_MEM,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 [1] = {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  .start = IRQ_LCD_VSYNC,                        //lcd中断寄存器起始地址，在s3cfb_probe用                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  .end   = IRQ_LCD_SYSTEM,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  .flags = IORESOURCE_IRQ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
};                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
static u64 s3c_device_lcd_dmamask = 0xffffffffUL;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
struct platform_device s3c_device_lcd = {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 .name    = "s3c-lcd",                                              //这个会和driver中的name一样，driver                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                             //根据这个进行匹配                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 .id    = -1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 .num_resources   = ARRAY_SIZE(s3c_lcd_resource),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
 .resource   = s3c_lcd_resource,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 .dev              = {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  .dma_mask  = &s3c_device_lcd_dmamask,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
  .coherent_dma_mask = 0xffffffffUL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
};                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//在arch/arm/mach-s3c6410/mach-smdk6410.c文件的                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//static void __init smdk6410_machine_init(void)函数中有这么一句话                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//platform_add_devices(smdk6410_devices, ARRAY_SIZE(smdk6410_devices));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//这个就是对device设备进行注册，在注册driver驱动时，会根据name找到相应的device进行匹配，然后会调用probe。                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//    下面分析driver，在drivers/video/samsung/s3cfb.c文件的最下面有这样的一段代码                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
static struct platform_driver s3cfb_driver = {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 .probe  = s3cfb_probe,                       //匹配的话会调用这个函数                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
 .remove  = s3cfb_remove,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 .suspend = s3cfb_suspend,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 .resume  = s3cfb_resume,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
        .driver  = {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  .name = "s3c-lcd",                                 //上面说的，内核会根据这个来找到相应的device                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  .owner = THIS_MODULE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
 },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
};                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
int __devinit s3cfb_init(void)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
 return platform_driver_register(&s3cfb_driver);//进行drive注册                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//匹配后会掉用s3cfb_probe（）；                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//这个函数里面对fbinfo进行初始化，对相关寄存器进行初始化，在6410lcd驱动中，主要要修改的几个文件是：drivers/video/samsung目录下的s3cfb.c，假设你在配置的时候即用make menuconfig命令，在里面选择的是480WV，他对应的文件时s3cfb_lte480wv.c，s3cfb_lte480wv.c是和屏参数相关的文件。还有个要改的文件是s3cfb_fimd4x.c,这个文件主要是涉及寄存器的一些参数的配置。                                                                                                                                                                                                                                                                                                                                                                                                                
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//    主要几个重点：对构架的分析，理清楚各个文件的关系。s3cfb.c中的s3cfb_probe主要是在根据s3cfb_fimd4x.c和s3cfb_lte480wv.c文件来初始fbinfo，并且写相关LCD寄存器。s3cfb_lte480wv.c主要是记录屏的参数，在这里进行修改来满足不同的lcd屏。s3cfb_fimd4x.c是对寄存器的值进行初始化，比如各个窗口的显示模式、颜色表寄存器的模式、各个窗口的控制寄存器，此文件还包含6410对于lcd的特殊功能，用ioctl来进行实现的。fbmem.c这个是fb字符设备驱动，每个窗口都是一个字符设备，在s3cfb_probe中通过调用register_buffer进行注册，注意，里面有一个fb_notifier_call_chain，他最终会调用drivers/video/console/fbcon.c中的fbcon_init，里面会有对logo的调用；fbmem.c文件里还有通用的ioctl功能调用，适合所有带lcd控制器的处理器，这个文件时通用的，每个处理器的fbmem都是一样的，做成了和硬件无关。
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        